# tfsec configuration
# https://aquasecurity.github.io/tfsec/latest/guides/configuration/

minimum_severity: MEDIUM

severity_overrides:
  # EKS endpoint public access - expected for testing
  aws-eks-no-public-cluster-access: LOW
  aws-eks-no-public-cluster-access-to-cidr: LOW

exclude:
  # These are intentionally configured for testing
  - aws-eks-encrypt-secrets  # May not have KMS key for tests
  - aws-eks-enable-control-plane-logging  # Logging configured separately

exclude_ignores:
  # Ensure these are never ignored in code
  - aws-iam-no-policy-wildcards
  - aws-vpc-no-public-ingress-sgr
  - aws-ec2-no-public-ip-subnet
